- name: Connect to AWS EC2 instance
  hosts: aws_instances
  become: true
  tasks:
    - name: Download docker installation script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Instal docker
      command: sh get-docker.sh