- name: Connect to AWS EC2 CICDCD instance
  hosts: aws_cicdcd_instance
  become: true
  tasks:
    - name: Download docker installation script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Instal docker
      command: sh get-docker.sh
    - name: Create Jenkins container
      command: sudo docker run --name jenkins_master -d -p 8080:8080 -p 50000:50000 --restart=on-failure jenkins/jenkins:lts-jdk17
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ../Jenkins_agents/
        dest: .
        mode: '777'
    - name: Copy private key to connect to others instances
      ansible.builtin.copy:
        src: ../Terraform/my-key
        dest: .
        mode: '777'

- name: Connect to AWS EC2 test instance
  hosts: aws_test_instance
  become: true
  tasks:
    - name: Download docker installation script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Instal docker
      command: sh get-docker.sh

- name: Connect to AWS EC2 production instance
  hosts: aws_production_instance
  become: true
  tasks:
    - name: Download docker installation script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Instal docker
      command: sh get-docker.sh
      
- name: Connect to AWS EC2 monitoring instance
  hosts: aws_monitoring_instance
  become: true
  tasks:
    - name: Download docker installation script
      command: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: Instal docker
      command: sh get-docker.sh